# Generated by Django 3.0.3 on 2020-02-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('nodeId', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('qualityLevel', models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='2', max_length=1)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modifiedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('waterMeterNo', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('userId', models.IntegerField(unique=True)),
                ('role', models.CharField(choices=[('CUST', 'customer'), ('ADMN', 'admin')], default='CUST', max_length=4)),
                ('qualtiyLevel', models.CharField(choices=[('1', 'low'), ('2', 'medium'), ('3', 'high')], default='M', max_length=1)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('modifiedAt', models.DateTimeField(auto_now_add=True)),
                ('path', models.ManyToManyField(related_name='path', to='monitoring.Node')),
                ('tapNode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tapnode', to='monitoring.Node')),
            ],
        ),
    ]
